// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBf2nH3IPyqsgTYcjkwZvtj97pybaPTBHo',
//     appId: '1:996786129707:web:d20cde5406657e9a5f536e',
//     messagingSenderId: '996786129707',
//     projectId: 'snap-focus-area',
//     authDomain: 'snap-focus-area.firebaseapp.com',
//     storageBucket: 'snap-focus-area.appspot.com',
//     measurementId: 'G-ZCWJYCP1W9',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDNMs3MqZy3j-9R2TMmvv1CZ4Vf6chffrs',
//     appId: '1:996786129707:android:655a85a87528d1955f536e',
//     messagingSenderId: '996786129707',
//     projectId: 'snap-focus-area',
//     storageBucket: 'snap-focus-area.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA1IkCQXV-U3wM-SxUwIYtnQnRp85ACH0M',
//     appId: '1:996786129707:ios:71e1acac4d0d5ee85f536e',
//     messagingSenderId: '996786129707',
//     projectId: 'snap-focus-area',
//     storageBucket: 'snap-focus-area.appspot.com',
//     iosBundleId: 'com.peervendors.snapFocusArea',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA1IkCQXV-U3wM-SxUwIYtnQnRp85ACH0M',
//     appId: '1:996786129707:ios:af00af64f570521d5f536e',
//     messagingSenderId: '996786129707',
//     projectId: 'snap-focus-area',
//     storageBucket: 'snap-focus-area.appspot.com',
//     iosBundleId: 'com.peervendors.snapFocusArea.RunnerTests',
//   );
// }
